version: "3"
services:
  shard:
    image: johnyburd/shard
    build:
      context: ./
      dockerfile: ./shard/Dockerfile
    env_file:
      - architus.env
    environment:
        - NUM_SHARDS
    deploy:
      replicas: "${NUM_SHARDS}"
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 500M
    depends_on:
      - manager
      - postgres
    networks:
      - webnet
  api:
    image: johnyburd/api
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    env_file:
      - architus.env
    environment:
        - NUM_SHARDS
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 500M
    ports:
      - "5000:5000"
    networks:
      - webnet
  websocket:
    image: johnyburd/websocket
    build:
      context: ./
      dockerfile: ./websocket/Dockerfile
    ports:
      - "6000:6000"
    networks:
      - webnet
  postgres:
    image: johnyburd/db:latest
    environment:
      POSTGRES_USER: autbot
      POSTGRES_PASSWORD: autism
      POSTGRES_DB: autbot
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  manager:
    image: johnyburd/manager:latest
    build:
      context: ./
      dockerfile: ./manager/Dockerfile
    environment:
        - NUM_SHARDS
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5300:5300"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  rabbit:
    image: johnyburd/rabbit
    build:
      context: ./
      dockerfile: ./rabbitmq/Dockerfile
    hostname: "rabbit"
    ports:
      - "8090:15672"
    networks:
      - webnet
networks:
  webnet:
