name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      NUM_SHARDS: 2

    steps:
    - uses: actions/checkout@v1
    - name: Environment garbage
      run: mv example.env architus.env
      run: export TAG=":${GITHUB_REF##*/}"

    - name: Build the Docker images
      run: docker-compose build

    - name: Push the images
      run: docker-compose push
