name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      NUM_SHARDS: 2

    steps:
    - uses: actions/checkout@v1
    - name: Environment garbage
      run: mv example.env architus.env

    - name: Build the Docker images
      run: TAG=":${GITHUB_REF##*/}" docker-compose build

    - uses: actions/docker/login@master
      env: 
        DOCKER_REGISTRY_URL: registry.hub.docker.com
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
    - name: Push the images
      run: TAG=":${GITHUB_REF##*/}" docker-compose push
