name: Build Docker Images

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      NUM_SHARDS: 2

    steps:
    - uses: actions/checkout@v1
    - name: Environment garbage
      run: mv example.env architus.env

    - name: Build the Docker image
      run: docker-compose build
